version: '3'
services:
  mongo-db:
    image: mongo
    ports:
      - "27017:27017" 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mymongo-data:/data/db  # Notice the corrected colon here

  mongo-express:
    image: mongo-express
    restart: always
    ports: 
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb  # Corrected reference to the mongo-db service

volumes:
  mymongo-data:
    driver: local
